---
- name: Install necessary packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - wget
  become: true
  tags: sample_db

- name: Clone the sample database repository
  git:
    repo: "https://github.com/datacharmer/test_db.git"
    dest: /tmp/test_db
    clone: yes
    update: yes
  become: true
  tags: sample_db

- name: Load the sample database
  shell: "mysql < employees.sql"
  args:
    chdir: /tmp/test_db
    executable: /bin/bash
  become: true
  ignore_errors: true
  tags: sample_db

- name: Test the sample database
  shell: "mysql -t < test_employees_md5.sql"
  args:
    chdir: /tmp/test_db
    executable: /bin/bash
  become: true
  ignore_errors: true
  tags: sample_db
