---
- name: Enable Blackhole storage engine
  command: mysql -e "INSTALL PLUGIN blackhole SONAME 'ha_blackhole';"
  become: true
  tags: sample_db

- name: Install necessary packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - wget
  become: true
  tags: sample_db

- name: Clone the sample database repository
  git:
    repo: "https://github.com/Ivanitch/sample-mysql-db.git"
    dest: /tmp/sample-mysql-db
    clone: yes
    update: yes
  become: true
  tags: sample_db

- name: Load the sample database
  shell: "mysql < employees.sql"
  args:
    chdir: /tmp/sample-mysql-db/employees
    executable: /bin/bash
  become: true
  ignore_errors: true
  tags: sample_db

- name: Test the sample database
  shell: "mysql -t < test_employees_md5.sql"
  args:
    chdir: /tmp/sample-mysql-db/employees
    executable: /bin/bash
  become: true
  ignore_errors: true
  tags: sample_db
