# roles/replica_master/tasks/main.yml
---
- name: Check if binary logging is enabled
  shell: >
    mysql -NBe "SHOW VARIABLES LIKE 'log_bin';" | grep -q ON
  register: binary_logging
  failed_when: false
  changed_when: false
  become: true
  tags: configure

- name: Read MariaDB root password from file
  slurp:
    src: /root/.mariapass
  register: mariapass
  become: true
  tags: configure

- name: Enable binary logging
  blockinfile:
    path: /etc/mysql/my.cnf
    block: |
      [mysqld]
      log_bin = /var/log/mysql/mysql-bin.log
      server_id = {{ ''.join(ansible_host.split('.')) }}
  when: binary_logging.rc != 0
  tags: configure

- name: Configure server as a master
  mysql_replication:
    mode: getprimary
    login_user: root
    login_password: "{{ mariapass['content'] | b64decode }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    primary_connect_retry: 60
    primary_use_gtid: current_pos
  tags: configure

- name: Restart mysql service
  service:
    name: mysql
    state: restarted
  when: binary_logging.rc != 0
  tags: configure

- name: Create replication user
  mysql_user:
    login_user: root
    login_password: "{{ mariapass['content'] | b64decode }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: replica_user
    password: "{{ replication_password }}"
    priv: "*.*:REPLICATION SLAVE"
    host: "%"
    state: present
  become: true
  tags: configure
