- name: Configure DBs
  hosts: mariadb
  become: true
  roles:
    - mariadb
  vars_files:
    - ../vault.yml

- name: ProxySQLs
  hosts: proxysql
  become: true
  roles:
    - proxysql
    - consul_agent

  vars_files:
    - ../vault.yml
