---
- name: proxysql | install | update apt cache
  apt:
    cache_valid_time: 14400
  changed_when: false
  ignore_errors: "{{ ansible_check_mode }}"

- name: proxysql | install | UFW
  apt:
    name: ufw
    state: present

- name: proxysql | install | Enable UFW
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: proxysql | install | install
  block:
    - name: proxysql | install | install platform specific prereqs
      apt:
        name: "{{ proxysql_prereqs }}"
        state: present
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: proxysql | install | install python packages
      pip:
        name: "{{ proxysql_python_packages }}"
        executable: pip3

  rescue:
    - name: proxysql | install | handle the error if we failed in check mode, with python-apt uninstalled
      assert:
        that: ansible_failed_result.msg is match("python-apt must be installed to use check mode.*")
        fail_msg: "unknown error during package install"
        success_msg: "running in check mode without python-apt installed, ignoring error"

  when: ansible_lsb.major_release|int > 14

- name: proxysql | install | install
  block:
    - name: proxysql | install | install proxysql release
      apt:
        deb: "{{ proxysql_release }}"
        state: present
      notify:
        - restart proxysql

  rescue:
    - name: proxysql | install | handle the error if we failed in check mode, with python-apt uninstalled
      assert:
        that: ansible_failed_result is search("python-apt must be installed to use check mode")
        fail_msg: "unknown error during package install"
        success_msg: "running in check mode without python-apt installed, ignoring error"

- name: proxysql | install | allow TCP traffic
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 22
    - 6032
    - 6033
    - 6070
    - 6080
  tags: ports

- name: proxysql | install | Enable and start ProxySQL service
  systemd:
    name: proxysql
    state: started
    enabled: true
  become: true
