---
- import_tasks: set_facts.yml
  tags:
    - always

- block:
    - import_tasks: system_user.yml
      tags:
        - users
        - config
    - import_tasks: install.yml
      tags:
        - install
  become: true
  become_user: root

- import_tasks: config.yml
  tags:
    - config
  become: true
  become_user: root

- import_tasks: post_install.yml
  tags:
    - post_install
  become: true
  become_user: root

- import_tasks: users.yml
  tags:
    - sync_users
  become: true
  become_user: root

- import_tasks: rules.yml
  tags:
    - rules
  become: true
  become_user: root
