---
- name: Read MariaDB root password from file
  slurp:
    src: /root/.mariapass
  register: mariapass
  become: true
  tags: configure

- name: Get the master host IP
  set_fact:
    master_host_ip: "{{ groups['master_db'][0] }}"
  tags: configure

- name: Stop server as a slave
  mysql_replication:
    mode: stopreplica
    login_user: root
    login_password: "{{ mariapass['content'] | b64decode }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags: configure

- name: Reset server as a slave
  mysql_replication:
    mode: resetreplica
    login_user: root
    login_password: "{{ mariapass['content'] | b64decode }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags: configure

- name: Configure server as a slave
  mysql_replication:
    mode: changeprimary
    master_host: "{{ master_host_ip }}"
    master_user: replica_user
    master_password: "{{ replication_password }}"
    login_user: root
    login_password: "{{ mariapass['content'] | b64decode }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags: configure

- name: Start server as a slave
  mysql_replication:
    mode: startreplica
    login_user: root
    login_password: "{{ mariapass['content'] | b64decode }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags: configure

- name: Restart mysql service
  service:
    name: mysql
    state: restarted
  tags: configure
